FROM openjdk:17-jdk

ENV LANGUAGE='en_US:en'

WORKDIR /deployments

COPY --chown=185 target/backend-1.O-SNAPSHOT.jar /deployments/app.jar

EXPOSE 8080

ENV JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"

ENTRYPOINT ["java", "-jar", "/deployments/app.jar"]